version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEMO_REDIS_ADDR=redis:6379
      - DEMO_APP_ADDR=:8000
    depends_on: 
        - redis
      
  redis:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: 1024
    ports: 
      - "6379:6379"
    volumes: 
      - ./data:/data
