---
- name: Setup Redis App
  hosts: all
  become: True

  tasks:
  - include_vars:
      file: sysctl-conf.vars 

  - name: Set a hostname
    hostname:
      name: demo-ops

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  

  - name: set timezone to Asia/Kolkata
    timezone:
      name: Asia/Kolkata
    
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker-ce and docker-compose
    apt:
      pkg:
        - docker-ce
        - docker-compose
      update_cache: yes
      install_recommends: yes
      state: present

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started

  - name: Add demo user to wheel group
    user:
      name: demo
      groups: wheel,docker
      append: yes
      state: present
      createhome: yes
      shell: /bin/bash

  - name: Increase nofile limits
    pam_limits:
      domain: demo
      limit_type: soft
      limit_item: nofile
      value: 64000

  - name: Change sysctl-conf
    sysctl:
      name: "{{ item.tunable }}"
      value: "{{ item.value }}"
      state: present
      reload: yes
    with_items: "{{ sysctl_config }}"

  - name: Copy dockerfile & app
    copy:
      src: ../bin/
      dest: /etc/demo-ops
      owner: demo
      group: demo

  - name: Copy dockerfile & app
    copy:
      src: counter-app.service
      dest: /etc/systemd/system/

  - name: Enable service httpd, and not touch the state
    service:
      name: counter-app
      enabled: yes

  - name: Ensure docker deamon is running
    service:
      name: counter-app
      state: started
